### ISSUE TITLE
运行报错，var_key not defined

### ISSUE THREAD

**Issue by gococ** [zigzag2050/mzphp2-deobfuscator#2]
运行报错，var_key not defined，如下图：
![360 16190821487092](https://user-images.githubusercontent.com/37581951/39803202-e9775550-53a2-11e8-83a8-5310b4b5836b.png)

具体php文件见附件
[site.zip](https://github.com/zigzag2050/mzphp2-deobfuscator/files/1986890/site.zip)

**Comment by zigzag2050** [comment]
你好，大致读了一下上传的php文件，文件很可能不是mzphp2加密的，里面没有发现mzphp2解密的关键数据结构，又或者mzphp的作者改进了加密方式。我的程序已经不适用了。
经过大约10分钟的简单观察，这个php似乎只是把变量名混淆成了不可读的字符串，程序逻辑看上去没有大的变动。如果对此php的运行逻辑有一定了解，可以采用全局文本替换的方法，手动恢复一部分变量名，不过会有比较大的工作量（也许恢复前用php-cs-fixer整理一下格式会有帮助）。
也许原php里的变量名是通过一些固定的规则混淆成现在的变量名的，如果能找到混淆规则，通过逆运算就可以恢复出原文。但我对此没有研究，如果您对此研究有所心得，还望不吝赐教。
